### ISSUE TITLE
How many clips do you use in TABLE III?

### ISSUE THREAD

**Issue by mzhaoshuai** [guoxih/region-based-non-local-network#4]
Thanks for your work.
I have a question.

In Table III, RNL got 49.47; while in Table V, RNL with 1 clip is 47.3.
In this case, could you please tell us why this difference occurs?
Did RNL in Table III uses 2 clips and 3 crops as said in the setting?
![image](https://user-images.githubusercontent.com/22476764/125628682-ce199477-7c18-42b1-9e9b-7d752dd0885f.png)
![image](https://user-images.githubusercontent.com/22476764/125628700-41b01cfd-5991-4089-910a-00380298a755.png)

**Comment by edhuang1** [comment]
Thank you for your question.

Yes, we use 2 clips and 3 crops in Table III, as stated in the setting.
But Table III reports the  FLOPS  of a single view, which can easily be misunderstood. Sorry about that.

**Comment by mzhaoshuai** [comment]
Thank you for your reply!
